In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#n_sensors = 3
#n_sensors = 5
#n_sensors = 10
n_sensors = 15

In [3]:
os.chdir('E:\\MLdataset\\vorticity_interpolation\\TSR1.5')

In [4]:
path = 'E:\\MLdataset\\TSR1.5_csv\\TSR1.5_csv\\'
file_list15 = os.listdir('E:\\MLdataset\\TSR1.5_csv\\TSR1.5_csv')
file_list_py15 = [file for file in file_list15 if file.endswith('.csv')]
df15 = pd.DataFrame()
for i in file_list_py15:
    data = pd.read_csv(path + i, header=None)
    df15 = pd.concat([df15, data], axis=0)

In [5]:
os.chdir('E:\\MLdataset\\TSR1.6_csv\\TSR1.6_csv')

In [6]:
path = 'E:\\MLdataset\\TSR1.6_csv\\TSR1.6_csv\\'
file_list16 = os.listdir('E:\\MLdataset\\TSR1.6_csv\\TSR1.6_csv')
file_list_py16 = [file for file in file_list16 if file.endswith('.csv')]
df16 = pd.DataFrame()
for i in file_list_py16:
    data = pd.read_csv(path + i, header=None)
    df16 = pd.concat([df16, data], axis=0)

In [7]:
os.chdir('E:\\MLdataset\\TSR1.7_3rev_5deg\\TSR1.7_3rev_5deg')

In [8]:
path = 'E:\\MLdataset\\TSR1.7_3rev_5deg\\TSR1.7_3rev_5deg\\'
file_list17 = os.listdir('E:\\MLdataset\\TSR1.7_3rev_5deg\\TSR1.7_3rev_5deg')
file_list_py17 = [file for file in file_list17 if file.endswith('.csv')]
df17 = pd.DataFrame()
for i in file_list_py17:
    data = pd.read_csv(path + i, header=None)
    df17 = pd.concat([df17, data], axis=0)

In [9]:
os.chdir('E:\\MLdataset\\TSR1.8_csv\\TSR1.8_csv')

In [10]:
path = 'E:\\MLdataset\\TSR1.8_csv\\TSR1.8_csv\\'
file_list18 = os.listdir('E:\\MLdataset\\TSR1.8_csv\\TSR1.8_csv')
file_list_py18 = [file for file in file_list18 if file.endswith('.csv')]
df18 = pd.DataFrame()
for i in file_list_py18:
    data = pd.read_csv(path + i, header=None)
    df18 = pd.concat([df18, data], axis=0)

In [11]:
os.chdir('E:\\MLdataset\\TSR1.9_csv\\TSR1.9_csv')

In [12]:
path = 'E:\\MLdataset\\TSR1.9_csv\\TSR1.9_csv\\'
file_list19 = os.listdir('E:\\MLdataset\\TSR1.9_csv\\TSR1.9_csv')
file_list_py19 = [file for file in file_list19 if file.endswith('.csv')]
df19 = pd.DataFrame()
for i in file_list_py19:
    data = pd.read_csv(path + i, header=None)
    df19 = pd.concat([df19, data], axis=0)

In [13]:
os.chdir('E:\\MLdataset\\TSR2_csv\\TSR2_csv')

In [14]:
path = 'E:\\MLdataset\\TSR2_csv\\TSR2_csv\\'
file_list20 = os.listdir('E:\\MLdataset\\TSR2_csv\\TSR2_csv')
file_list_py20 = [file for file in file_list20 if file.endswith('.csv')]
df20 = pd.DataFrame()
for i in file_list_py20:
    data = pd.read_csv(path + i, header=None)
    df20 = pd.concat([df20, data], axis=0)

In [15]:
os.chdir('E:\\MLdataset')

In [16]:
vor15 = df15.to_numpy(dtype='float32')
vor16 = df16.to_numpy(dtype='float32')
vor17 = df17.to_numpy(dtype='float32')
vor18 = df18.to_numpy(dtype='float32')
vor19 = df19.to_numpy(dtype='float32')
vor20 = df20.to_numpy(dtype='float32')

In [17]:
v15 = vor15.reshape((217, 100, 100))
v16 = vor16.reshape((217, 100, 100))
v17 = vor17.reshape((217, 100, 100))
v18 = vor18.reshape((217, 100, 100))
v19 = vor19.reshape((217, 100, 100))
v20 = vor20.reshape((217, 100, 100))

In [18]:
x_train15 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train15[i, j, k] = v15[i, 25*j, 13*k+23]
x_train16 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train16[i, j, k] = v16[i, 25*j, 13*k+23]
x_train17 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train17[i, j, k] = v17[i, 25*j, 13*k+23]
x_train18 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train18[i, j, k] = v18[i, 25*j, 13*k+23]
x_train19 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train19[i, j, k] = v19[i, 25*j, 13*k+23]
x_train20 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train20[i, j, k] = v20[i, 25*j, 13*k+23]

In [19]:
x_train15

array([[[-0.011075  ,  0.61225998,  0.022469  , -0.041157  ,
         -0.065419  ],
        [ 0.029312  ,  0.16134   ,  0.073005  , -0.001264  ,
         -0.067523  ],
        [ 0.15064   ,  0.070647  ,  0.0051201 , -0.027652  ,
         -0.10223   ]],

       [[-0.0058821 ,  0.62121999, -0.0050366 , -0.044391  ,
         -0.064274  ],
        [ 0.043147  ,  0.15734001,  0.065417  ,  0.0029061 ,
         -0.076842  ],
        [ 0.1159    ,  0.068597  ,  0.0076461 , -0.035891  ,
         -0.10579   ]],

       [[-0.0072923 ,  0.60508001, -0.032551  , -0.047902  ,
         -0.066807  ],
        [ 0.056707  ,  0.1516    ,  0.056716  ,  0.0063621 ,
         -0.087979  ],
        [ 0.081174  ,  0.067934  ,  0.0096331 , -0.044973  ,
         -0.10951   ]],

       ...,

       [[-0.048306  ,  0.57712001,  0.059417  , -0.039639  ,
         -0.078188  ],
        [ 0.0070455 ,  0.17659999,  0.17563   , -0.012009  ,
         -0.05859   ],
        [ 0.14617001,  0.068849  ,  0.023338  , -0.027481

In [20]:
x_train15.reshape((217, 15))

array([[-0.011075  ,  0.61225998,  0.022469  , ...,  0.0051201 ,
        -0.027652  , -0.10223   ],
       [-0.0058821 ,  0.62121999, -0.0050366 , ...,  0.0076461 ,
        -0.035891  , -0.10579   ],
       [-0.0072923 ,  0.60508001, -0.032551  , ...,  0.0096331 ,
        -0.044973  , -0.10951   ],
       ...,
       [-0.048306  ,  0.57712001,  0.059417  , ...,  0.023338  ,
        -0.027481  , -0.091588  ],
       [-0.02998   ,  0.61556   ,  0.039146  , ...,  0.024526  ,
        -0.034421  , -0.09488   ],
       [-0.014869  ,  0.62851   ,  0.01267   , ...,  0.025167  ,
        -0.042572  , -0.097864  ]])

In [21]:
x_5deg = np.vstack((x_train15.reshape((217, 15)), x_train16.reshape((217, 15)), x_train17.reshape((217, 15)),
                    x_train18.reshape((217, 15)), x_train19.reshape((217, 15)), x_train20.reshape((217, 15))))

In [22]:
x_case2 = np.vstack((x_train15[:73,:].reshape((73, 15)), x_train16[:73,:].reshape((73, 15)), x_train17[:73,:].reshape((73, 15)),
                    x_train18[:73,:].reshape((73, 15)), x_train19[:73,:].reshape((73, 15)), x_train20[:73,:].reshape((73, 15))))

In [23]:
print(x_5deg.shape)

(1302, 15)


In [24]:
x_train15_10deg = x_train15[::2].reshape(((36*3+1), 15))
x_train16_10deg = x_train16[::2].reshape(((36*3+1), 15))
x_train17_10deg = x_train17[::2].reshape(((36*3+1), 15))
x_train18_10deg = x_train18[::2].reshape(((36*3+1), 15))
x_train19_10deg = x_train19[::2].reshape(((36*3+1), 15))
x_train20_10deg = x_train20[::2].reshape(((36*3+1), 15))

In [25]:
x_10deg = np.vstack((x_train15_10deg, x_train16_10deg, x_train17_10deg, x_train18_10deg, x_train19_10deg, x_train20_10deg))

In [13]:
tsr_10deg = np.vstack((1.5*np.ones((36*3+1,1)), 1.6*np.ones((36*3+1,1)), 1.7*np.ones((36*3+1,1)), 1.8*np.ones((36*3+1,1)),
                       1.9*np.ones((36*3+1,1)), 2.0*np.ones((36*3+1,1))))
tsr_5deg = np.vstack((1.5*np.ones((72*3+1,1)), 1.6*np.ones((72*3+1,1)), 1.7*np.ones((72*3+1,1)), 1.8*np.ones((72*3+1,1)),
                      1.9*np.ones((72*3+1,1)), 2.0*np.ones((72*3+1,1))))
theta_10 = np.linspace(0, 1080, 36*3+1)
theta_5 = np.linspace(0, 1080, 72*3+1)

In [27]:
theta_5

array([   0.,    5.,   10.,   15.,   20.,   25.,   30.,   35.,   40.,
         45.,   50.,   55.,   60.,   65.,   70.,   75.,   80.,   85.,
         90.,   95.,  100.,  105.,  110.,  115.,  120.,  125.,  130.,
        135.,  140.,  145.,  150.,  155.,  160.,  165.,  170.,  175.,
        180.,  185.,  190.,  195.,  200.,  205.,  210.,  215.,  220.,
        225.,  230.,  235.,  240.,  245.,  250.,  255.,  260.,  265.,
        270.,  275.,  280.,  285.,  290.,  295.,  300.,  305.,  310.,
        315.,  320.,  325.,  330.,  335.,  340.,  345.,  350.,  355.,
        360.,  365.,  370.,  375.,  380.,  385.,  390.,  395.,  400.,
        405.,  410.,  415.,  420.,  425.,  430.,  435.,  440.,  445.,
        450.,  455.,  460.,  465.,  470.,  475.,  480.,  485.,  490.,
        495.,  500.,  505.,  510.,  515.,  520.,  525.,  530.,  535.,
        540.,  545.,  550.,  555.,  560.,  565.,  570.,  575.,  580.,
        585.,  590.,  595.,  600.,  605.,  610.,  615.,  620.,  625.,
        630.,  635.,

In [28]:
print(theta_5.shape)

(217,)


In [29]:
theta_10 = theta_10.reshape(36*3+1,1)
theta_5 = theta_5.reshape(72*3+1,1)

In [30]:
theta_10deg = np.vstack((theta_10, theta_10, theta_10, theta_10, theta_10, theta_10))

In [31]:
theta_5deg = np.vstack((theta_5, theta_5, theta_5, theta_5, theta_5, theta_5))

In [32]:
theta_case2 = np.linspace(0, 360, 73).reshape((73, 1))
theta_case2 = np.vstack((theta_case2, theta_case2, theta_case2, theta_case2, theta_case2, theta_case2))
tsr_case2 = np.vstack((1.5*np.ones((73,1)), 1.6*np.ones((73,1)), 1.7*np.ones((73,1)), 1.8*np.ones((73,1)),
                       1.9*np.ones((73,1)), 2.0*np.ones((73,1))))

In [33]:
x_sensor_10deg = np.hstack((x_10deg, tsr_10deg, theta_10deg))

In [34]:
x_sensor_5deg = np.hstack((x_5deg, tsr_5deg, theta_5deg))

In [35]:
x_sensor_10deg.shape

(654, 17)

In [36]:
x_case2 = np.hstack((x_case2, tsr_case2, theta_case2))

In [37]:
x_sensor_10deg

array([[-1.10750003e-02,  6.12259984e-01,  2.24690009e-02, ...,
        -1.02229998e-01,  1.50000000e+00,  0.00000000e+00],
       [-7.29230000e-03,  6.05080009e-01, -3.25510018e-02, ...,
        -1.09509997e-01,  1.50000000e+00,  1.00000000e+01],
       [-2.86799995e-03,  5.11039972e-01, -7.64190033e-02, ...,
        -1.15850002e-01,  1.50000000e+00,  2.00000000e+01],
       ...,
       [ 5.32869995e-02,  4.82179999e-01, -4.90689993e-01, ...,
        -1.11910000e-01,  2.00000000e+00,  1.06000000e+03],
       [ 1.37449997e-02,  3.05990010e-01, -5.78679979e-01, ...,
        -1.15209997e-01,  2.00000000e+00,  1.07000000e+03],
       [-1.17450003e-02,  1.62009999e-01, -5.00389993e-01, ...,
        -1.20030001e-01,  2.00000000e+00,  1.08000000e+03]])

In [38]:
x_case2

array([[-1.10750003e-02,  6.12259984e-01,  2.24690009e-02, ...,
        -1.02229998e-01,  1.50000000e+00,  0.00000000e+00],
       [-5.88210020e-03,  6.21219993e-01, -5.03659993e-03, ...,
        -1.05789997e-01,  1.50000000e+00,  5.00000000e+00],
       [-7.29230000e-03,  6.05080009e-01, -3.25510018e-02, ...,
        -1.09509997e-01,  1.50000000e+00,  1.00000000e+01],
       ...,
       [ 1.68319996e-02,  2.93419987e-01, -6.97849989e-01, ...,
        -1.08609997e-01,  2.00000000e+00,  3.50000000e+02],
       [ 1.65009999e-03,  2.18219995e-01, -7.20130026e-01, ...,
        -1.09660000e-01,  2.00000000e+00,  3.55000000e+02],
       [-9.91849974e-03,  1.50189996e-01, -6.85940027e-01, ...,
        -1.11019999e-01,  2.00000000e+00,  3.60000000e+02]])

In [39]:
np.savetxt('x_10degree_new.csv', x_sensor_10deg, delimiter=",")
np.savetxt('x_5degree_new.csv', x_sensor_5deg, delimiter=",")

In [40]:
np.savetxt('x_5degree_1rev_new.csv', x_case2, delimiter=",")

In [41]:
x_case1 = np.vstack((x_train15[:37,:].reshape((37, 15)), x_train16[:37,:].reshape((37, 15)), x_train17[:37,:].reshape((37, 15)),
                    x_train18[:37,:].reshape((37, 15)), x_train19[:37,:].reshape((37, 15)), x_train20[:37,:].reshape((37, 15))))

In [42]:
theta_case1 = np.linspace(0, 360, 37).reshape((37, 1))
theta_case1 = np.vstack((theta_case1, theta_case1, theta_case1, theta_case1, theta_case1, theta_case1))
tsr_case1 = np.vstack((1.5*np.ones((37,1)), 1.6*np.ones((37,1)), 1.7*np.ones((37,1)), 1.8*np.ones((37,1)),
                       1.9*np.ones((37,1)), 2.0*np.ones((37,1))))

In [43]:
x_case1 = np.hstack((x_case1, tsr_case1, theta_case1))

In [44]:
x_case1

array([[-1.10750003e-02,  6.12259984e-01,  2.24690009e-02, ...,
        -1.02229998e-01,  1.50000000e+00,  0.00000000e+00],
       [-5.88210020e-03,  6.21219993e-01, -5.03659993e-03, ...,
        -1.05789997e-01,  1.50000000e+00,  1.00000000e+01],
       [-7.29230000e-03,  6.05080009e-01, -3.25510018e-02, ...,
        -1.09509997e-01,  1.50000000e+00,  2.00000000e+01],
       ...,
       [ 1.95960000e-01, -2.25380003e-01,  2.02680007e-01, ...,
        -1.70790002e-01,  2.00000000e+00,  3.40000000e+02],
       [ 2.19569996e-01, -3.31039995e-01,  2.51690000e-01, ...,
        -1.68290004e-01,  2.00000000e+00,  3.50000000e+02],
       [ 2.25930005e-01, -4.18150008e-01,  2.88159996e-01, ...,
        -1.65580004e-01,  2.00000000e+00,  3.60000000e+02]])

In [45]:
np.savetxt('x_10degree_1rev_new.csv', x_case1, delimiter=",")

In [46]:
theta_120_5degree = np.linspace(0, 120, 25).reshape((25, 1))
theta_120_10degree = np.linspace(0, 120, 13).reshape((13, 1))
theta_120_5degree = np.vstack((theta_120_5degree, theta_120_5degree, theta_120_5degree,
                               theta_120_5degree, theta_120_5degree, theta_120_5degree))
theta_120_10degree = np.vstack((theta_120_10degree, theta_120_10degree, theta_120_10degree,
                                theta_120_10degree, theta_120_10degree, theta_120_10degree))
tsr_120_5degree = np.vstack((1.5*np.ones((25,1)), 1.6*np.ones((25,1)), 1.7*np.ones((25,1)), 1.8*np.ones((25,1)),
                             1.9*np.ones((25,1)), 2.0*np.ones((25,1))))
tsr_120_10degree = np.vstack((1.5*np.ones((13,1)), 1.6*np.ones((13,1)), 1.7*np.ones((13,1)), 1.8*np.ones((13,1)),
                              1.9*np.ones((13,1)), 2.0*np.ones((13,1))))

In [47]:
x_120_5 = np.vstack((x_train15[:25,:].reshape((25, 15)), x_train16[:25,:].reshape((25, 15)),
                     x_train17[:25,:].reshape((25, 15)), x_train18[:25,:].reshape((25, 15)),
                     x_train19[:25,:].reshape((25, 15)), x_train20[:25,:].reshape((25, 15))))
x_120_10 = np.vstack((x_train15_10deg[:13,:].reshape((13, 15)), x_train16_10deg[:13,:].reshape((13, 15)),
                      x_train17_10deg[:13,:].reshape((13, 15)), x_train18_10deg[:13,:].reshape((13, 15)),
                      x_train19_10deg[:13,:].reshape((13, 15)), x_train20_10deg[:13,:].reshape((13, 15))))

In [48]:
x_120_5degree = np.hstack((x_120_5, tsr_120_5degree, theta_120_5degree))
x_120_10degree = np.hstack((x_120_10, tsr_120_10degree, theta_120_10degree))

In [49]:
np.savetxt('x_120_5degree.csv', x_120_5degree, delimiter=",")
np.savetxt('x_120_10degree.csv', x_120_10degree, delimiter=",")

In [53]:
x_120_10degree_15train = x_train15_10deg[:13,:][::2].reshape((7, 15))
x_120_10degree_16train = x_train16_10deg[:13,:][::2].reshape((7, 15))
x_120_10degree_17train = x_train17_10deg[:13,:][::2].reshape((7, 15))
x_120_10degree_18train = x_train18_10deg[:13,:][::2].reshape((7, 15))
x_120_10degree_19train = x_train19_10deg[:13,:][::2].reshape((7, 15))
x_120_10degree_20train = x_train20_10deg[:13,:][::2].reshape((7, 15))

In [65]:
x_120_10degree_15test = x_train15_10deg[:13,:][1::2].reshape((6, 15))
x_120_10degree_16test = x_train16_10deg[:13,:][1::2].reshape((6, 15))
x_120_10degree_17test = x_train17_10deg[:13,:][1::2].reshape((6, 15))
x_120_10degree_18test = x_train18_10deg[:13,:][1::2].reshape((6, 15))
x_120_10degree_19test = x_train19_10deg[:13,:][1::2].reshape((6, 15))
x_120_10degree_20test = x_train20_10deg[:13,:][1::2].reshape((6, 15))

In [66]:
x_120_case5_train = np.vstack((x_120_10degree_15train, x_120_10degree_16train,
                               x_120_10degree_17train, x_120_10degree_18train,
                               x_120_10degree_19train, x_120_10degree_20train))
x_120_case5_test = np.vstack((x_120_10degree_15test, x_120_10degree_16test,
                              x_120_10degree_17test, x_120_10degree_18test,
                              x_120_10degree_19test, x_120_10degree_20test))

In [67]:
tsr_120_case5_train = np.vstack((1.5*np.ones((7,1)), 1.6*np.ones((7,1)), 1.7*np.ones((7,1)), 1.8*np.ones((7,1)),
                                 1.9*np.ones((7,1)), 2.0*np.ones((7,1))))
tsr_120_case5_test = np.vstack((1.5*np.ones((6,1)), 1.6*np.ones((6,1)), 1.7*np.ones((6,1)), 1.8*np.ones((6,1)),
                                1.9*np.ones((6,1)), 2.0*np.ones((6,1))))
theta_120_case5_train = np.linspace(0, 120, 7).reshape((7, 1))
theta_120_case5_test = np.linspace(10, 110, 6).reshape((6, 1))
theta_120_case5_train = np.vstack((theta_120_case5_train, theta_120_case5_train, theta_120_case5_train,
                                   theta_120_case5_train, theta_120_case5_train, theta_120_case5_train))
theta_120_case5_test = np.vstack((theta_120_case5_test, theta_120_case5_test, theta_120_case5_test,
                                  theta_120_case5_test, theta_120_case5_test, theta_120_case5_test))

In [69]:
x_case5_train = np.hstack((x_120_case5_train, tsr_120_case5_train, theta_120_case5_train))
x_case5_test = np.hstack((x_120_case5_test, tsr_120_case5_test, theta_120_case5_test))

In [74]:
np.savetxt('x_case5_train.csv', x_case5_train, delimiter=",")
np.savetxt('x_case5_test.csv', x_case5_test, delimiter=",")

In [76]:
x_120_5degree_15train = x_train15[:25,:][::2].reshape((13, 15))
x_120_5degree_16train = x_train16[:25,:][::2].reshape((13, 15))
x_120_5degree_17train = x_train17[:25,:][::2].reshape((13, 15))
x_120_5degree_18train = x_train18[:25,:][::2].reshape((13, 15))
x_120_5degree_19train = x_train19[:25,:][::2].reshape((13, 15))
x_120_5degree_20train = x_train20[:25,:][::2].reshape((13, 15))

In [77]:
x_120_5degree_15test = x_train15[:25,:][1::2].reshape((12, 15))
x_120_5degree_16test = x_train16[:25,:][1::2].reshape((12, 15))
x_120_5degree_17test = x_train17[:25,:][1::2].reshape((12, 15))
x_120_5degree_18test = x_train18[:25,:][1::2].reshape((12, 15))
x_120_5degree_19test = x_train19[:25,:][1::2].reshape((12, 15))
x_120_5degree_20test = x_train20[:25,:][1::2].reshape((12, 15))

In [78]:
x_120_case6_train = np.vstack((x_120_5degree_15train, x_120_5degree_16train,
                               x_120_5degree_17train, x_120_5degree_18train,
                               x_120_5degree_19train, x_120_5degree_20train))
x_120_case6_test = np.vstack((x_120_5degree_15test, x_120_5degree_16test,
                              x_120_5degree_17test, x_120_5degree_18test,
                              x_120_5degree_19test, x_120_5degree_20test))

In [79]:
tsr_120_case6_train = np.vstack((1.5*np.ones((13,1)), 1.6*np.ones((13,1)), 1.7*np.ones((13,1)), 1.8*np.ones((13,1)),
                                 1.9*np.ones((13,1)), 2.0*np.ones((13,1))))
tsr_120_case6_test = np.vstack((1.5*np.ones((12,1)), 1.6*np.ones((12,1)), 1.7*np.ones((12,1)), 1.8*np.ones((12,1)),
                                1.9*np.ones((12,1)), 2.0*np.ones((12,1))))
theta_120_case6_train = np.linspace(0, 120, 13).reshape((13, 1))
theta_120_case6_test = np.linspace(5, 115, 12).reshape((12, 1))
theta_120_case6_train = np.vstack((theta_120_case6_train, theta_120_case6_train, theta_120_case6_train,
                                   theta_120_case6_train, theta_120_case6_train, theta_120_case6_train))
theta_120_case6_test = np.vstack((theta_120_case6_test, theta_120_case6_test, theta_120_case6_test,
                                  theta_120_case6_test, theta_120_case6_test, theta_120_case6_test))

In [80]:
x_case6_train = np.hstack((x_120_case6_train, tsr_120_case6_train, theta_120_case6_train))
x_case6_test = np.hstack((x_120_case6_test, tsr_120_case6_test, theta_120_case6_test))

In [81]:
np.savetxt('x_case6_train.csv', x_case6_train, delimiter=",")
np.savetxt('x_case6_test.csv', x_case6_test, delimiter=",")

In [3]:
os.chdir('E:\\MLdataset\\TSR1.75_vorticity\\TSR1.75_vorticity')

In [4]:
path = 'E:\\MLdataset\\TSR1.75_vorticity\\TSR1.75_vorticity\\'
file_list175 = os.listdir('E:\\MLdataset\\TSR1.75_vorticity\\TSR1.75_vorticity')
file_list_py175 = [file for file in file_list175 if file.endswith('.csv')]
df175 = pd.DataFrame()
for i in file_list_py175:
    data = pd.read_csv(path + i, header=None)
    df175 = pd.concat([df175, data], axis=0)

In [5]:
os.chdir('E:\\MLdataset')

In [6]:
vor175 = df175.to_numpy(dtype='float32')

In [7]:
vor175_10deg = vor175.reshape((217, 100, 100))[::2].reshape(((36*3+1)*100, 100))

In [8]:
y_175_5deg =vor175.reshape((72*3+1, 100, 100))

In [9]:
v175 = vor175.reshape((217, 100, 100))

In [10]:
x_train175 = np.zeros((217, 3, 5))
for i in range(0, 217):
    for j in range(0, 3):
        for k in range(0, 5):
            x_train175[i, j, k] = v175[i, 25*j, 13*k+23]

In [11]:
x_train175_10deg = x_train175[::2].reshape(((36*3+1), 15))

In [15]:
x_case175 = np.hstack((x_train175_10deg, 1.75*np.ones((36*3+1,1)).reshape((36*3+1, 1)), theta_10.reshape((-1,1))))

In [16]:
np.savetxt('x_175(10degree).csv', x_case175, delimiter=",")